// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yoezezhdzubxlzgrqkuz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvZXplemhkenVieGx6Z3Jxa3V6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNjE1MDksImV4cCI6MjA2MDYzNzUwOX0.LKsZu6MaQsMnFOWp893hdqPcDORbZ2yl9Ts4hg_dLKo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);